-- table supabase
-- @vlxyzo
CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  telegram_id BIGINT UNIQUE NOT NULL,
  username TEXT,
  first_name TEXT,
  last_name TEXT,
  user_limit INT DEFAULT 10,
  warning INT DEFAULT 0,
  is_owner BOOLEAN DEFAULT FALSE,
  is_banned BOOLEAN DEFAULT FALSE,
  info JSONB DEFAULT '{}'::jsonb
);
