/**
 * 版权所有。允许个人和商业使用及修改。
 * 重新分发请严格遵循 GPL-V3.0 协议，且请勿声称原创。
 *
 * 项目  :  Zero Two v0.0.1-alpha
 * 作者  :  Velix
 * 协议  :  GPL-V3.0
 * 源码  :  github.com/vlxyzo/zerotwo
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];
export type TelegramId = bigint;
export type IdInput = bigint | number | string;
export type ChatType = 'private' | 'group' | 'supergroup' | 'channel';
const valid_types: readonly ChatType[] = ['private', 'group', 'supergroup', 'channel'];

export function isChat(value: string): value is ChatType {
	return (valid_types as readonly string[]).includes(value);
}

export function toTeleId(value: IdInput): TelegramId {
	if (typeof value === 'bigint') return value;
	if (typeof value === 'number') {
		if (!Number.isInteger(value))
			throw new TypeError(`toTeleId: This ${value} is not an integer`);
		return BigInt(value);
	}

	if (/^-?\d+$/.test(value)) return BigInt(value);
	throw new TypeError(`toTeleId: This ${value} is not a valid integer id`);
}

export function toDbId(value: TelegramId | IdInput): number {
	const id = typeof value === 'bigint' ? value : toTeleId(value);
	if (id > BigInt(Number.MAX_SAFE_INTEGER) || id < BigInt(Number.MIN_SAFE_INTEGER)) {
		throw new RangeError(`toDbId: This ${id} exceeds javascript safe integer range`);
	}

	return Number(id);
}

// sql table ----
// CREATE TABLE users (
//   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//   "telegramID" BIGINT UNIQUE NOT NULL,
//   username TEXT,
//   first_name TEXT,
//   last_name TEXT,
//   "limit" INT DEFAULT 10,
//   warning INT DEFAULT 0,
//   "isOwner" BOOLEAN DEFAULT FALSE,
//   "isBanned" BOOLEAN DEFAULT FALSE,
//   info JSONB DEFAULT '{}'::jsonb
// );
// ----

export interface UserRow<TInfo extends Json = Json> {
	id: number;
	telegramID: number;
	username: string | null;
	first_name: string | null;
	last_name: string | null;
	limit: number | null;
	warning: number | null;
	isOwner: boolean | null;
	isBanned: boolean | null;
	info: TInfo | null;
}

export interface UserInsert<TInfo extends Json = Json> {
	id?: number;
	telegramID: number;
	username?: string | null;
	first_name?: string | null;
	last_name?: string | null;
	limit?: number | null;
	warning?: number | null;
	isOwner?: boolean | null;
	isBanned?: boolean | null;
	info?: TInfo | null;
}

export type UserUpdate = Partial<Omit<UserInsert, 'id'>> & { id: TelegramId };
